### PR TITLE
fix: Persist log in a file

### PR DESCRIPTION
**Pull request by realekhor**

### CODE REVIEW

**Comment by tdashworth** [comment]
Hi @realekhor, I have the latest version but I'm not seeing a change? 

image

image

**Comment by realekhor** [comment]
i had the same issue while debugging it yesterday. not sure why it seems to "lag". will investigate this.

**Comment by tdashworth** [comment]
@realekhor could we stick to the topic of this PR, lengthening the fields for file/folder inputs? 

I would like to discuss the logging changes separately if that's okay.

**Comment by realekhor** [comment]
sure.

**Review by markcunninghamuk — APPROVED** [review]

**Pull request merged**
