### PR TITLE
ci: release to Nuget

### PR DESCRIPTION
**Pull request by tdashworth**
update pipeline to align with our best practices

### CODE REVIEW

**Comment by tdashworth** [comment]
@ewingjm Any idea why this is failing? I switched the restore from Nuget to DotNet. Should I just revert that?

**Comment by realekhor** [comment]
@tdashworth  i will fix this

**Comment by tdashworth** [comment]
I have added a tag for the last release to NuGet. Not sure if that will reset GitVersion to v1.0.6. @ewingjm?

**Comment by tdashworth** [comment]
Do we need to add [this ](https://gitversion.net/docs/usage/msbuild)to update the assembly version as well? Not just the NuGet package version?

**Comment by ewingjm** [comment]
> Do we need to add [this ](https://gitversion.net/docs/usage/msbuild)to update the assembly version as well? Not just the NuGet package version?

Shouldn't need to as it's already handled by the GitVersion task in the pipeline.

**Comment by ewingjm** [comment]
> I have added a tag for the last release to NuGet. Not sure if that will reset GitVersion to v1.0.6. @ewingjm?

You'll need to the latest commit on the master branch for whatever the current version is.

**Comment by tdashworth** [comment]
> > I have added a tag for the last release to NuGet. Not sure if that will reset GitVersion to v1.0.6. @ewingjm?
> 
> You'll need to tag the latest commit on the master branch for whatever the current version is.

Do we want to start on a new version? e.g. v1.1.0?

**Comment by ewingjm** [comment]
> > > I have added a tag for the last release to NuGet. Not sure if that will reset GitVersion to v1.0.6. @ewingjm?
> > 
> > 
> > You'll need to tag the latest commit on the master branch for whatever the current version is.
> 
> Do we want to start on a new version? e.g. v1.1.0?

if you tag a commit with a version that isn't on NuGet then we'll effectively skip a version. Whichever commit is currently deployed to NuGet should be tagged with a matching version. When the PR is merged, it'll use the commit message to apply the next version on top of this. Putting `+semver: minor` in the squash commit message should be enough if the current version was tagged.

**Review by ewingjm — APPROVED** [review]

**Pull request merged**
